### PR TITLE
Karl's Rework to continue improving, reset_position

### PR DESCRIPTION
**Pull request by TheZeroBeast**
Karl's Rework to continue improving
reset_position after rehome on stall implemented

### CODE REVIEW

**Comment by AbeFM** [comment]
Er.. is this this https://github.com/KarlZeilhofer/MM-control-01/issues/2?

I'm getting further out of my depth every minute here. But I'm trying to hang with the developers. :-)

**Comment by TheZeroBeast** [comment]
Hi AbeFM, sure is.

I'm pushing his changes to the entire codebase, removing PRUSAs efforts and plan to do some test prints later this week if everything goes good.

Test print with the hack I did to get his smooth code printing last night went good although stallguard on idler is a tad sensitive, triggering sometimes on filament load/unload which doesn't recover correct as yet.

**Comment by AbeFM** [comment]
Is that it? I keep finding failed loads with no real reason - possibly it's
over-extracting on unloading. Generally just hitting the buttons makes it
work.

I'm kinda doing other stuff today so I'm not just watching it run - a bad
way to debug but hey its free.

**Comment by TheZeroBeast** [comment]
Yeah, still miles to go and as we the public seam to have to do this our selves brute force testing is all we have. I just did another couple hours of clean up in prep for testing under branch Patch-1, I'll see if Karl is able to look over it before as he is a serious guru with AVR and Trinamic coding.

**Comment by AbeFM** [comment]
As a user, it kills me there's no easy way to get it to pick up from an error.

I think some of my issues today were new bowden tubes on the mmu being poorly seated. :-(

**Comment by TheZeroBeast** [comment]
Yes, as a user that paid good money for a half baked upgrade I am among a lot that are very upset with their efforts.

It has the ability to be smarter as it has cutting edge stepper drivers.

Yes, I actually used a 2.5mm drill and reamed out 20mm or so of the 5 filaments going into the MMU2 then clamped quite hard. Haven't had another come out and resistance is low through there now.

**Comment by AbeFM** [comment]
That is not a bad idea. Certainly the tubes don't need to be tight there.

I'm a little upset by the implications of making us wait the better part of a year and THEN sending out junk, I'm FAR more upset about the fingers in their ears anytime someone points out where it could be improved.

I've had some weird stopages in the first filament change, not doing enough prints to get a feel for it yet, but it;s weird and I don't know if it's mechanical, logic, and where/

**Pull request merged**
