### PR TITLE
Removed Bowden Length Cal - Cleaning Code

### PR DESCRIPTION
**Pull request by TheZeroBeast**

### CODE REVIEW

**Comment by AbeFM** [comment]
Not sure where to comment, and last several questions have gone unanswered, not sure how to be useful here.

The old version I was running, when there was a misfeed, kept trying to cut and fed and cut and feed and I had dinner to come back and find some 10+ meters of filament squirted out on the floor. It had missed the selector and just kept feeding.

IT IS IMPERATIVE that the machine fail "safe". After some FINITE number of attempts, there is no reason to keep trying, you can only cause trouble or do no further improvement.

I installed the latest version, and had issues. The print will not load the filament when the print begins. During the prime line, the MMU feeds (much, much slower than before, the same for retracts, much slower), and gets into the extruder gears, but won't start printing until several CM of filament is "used up" in the "print".

**Comment by AbeFM** [comment]
Ah! Great, good to hear a voice on the other end.

Perhaps "master" or... "stable" would make sense?

Is there a version to get that works with stock firmware, or... I guess the updated printer FW to go with it?

**Comment by AbeFM** [comment]
Oh, found the code (from the readme: https://github.com/TheZeroBeast/Prusa-Firmware/tree/MMU-MK3-FSensorBuild/Firmware )

Just want to make sure before I overwrite EVERYTHING that it's at least the right thing. I'd certainly like to see a "stable" (stock FW compatible) MMU FW that people can try - can you expose/identify that? That stuff I was running before seemed ok aside from not giving up when it should.

**Comment by TheZeroBeast** [comment]
Yeah man, master is as close to stable at the moment. Once it’s working reliably on my mmu2 I’ll let everyone know, then each feature implementation will have a branch for testing before merging into master.

Yes, that’s the FW 👍👌 if you watch the terminal feed of the printer you should see messages about waiting for printer sensor trigger and advising mmu of trigger.

If filament stuffs up and doesn’t make it it won’t continue.

At this point you should be able to fix the problem. Ensure filament is out back to load position and press middle button to try again and continue.

Let me know how you go 👍

**Comment by AbeFM** [comment]
So - no version that works with stock MK3 firmware, but if I install the above on the printer AND the firmware for the MMU on master, we should have a functional pair?

**Comment by AbeFM** [comment]
I don't see a clone button, I guess a pull request would work...?

**Comment by TheZeroBeast** [comment]
Yes, that is the functional pair.

There should be a clone button when at top git folder level

**Comment by AbeFM** [comment]
image

**Comment by AbeFM** [comment]
Firmware MMU:
2.0.2-158
Firmware Printer:
3.4.2-1360

Same behavior - printer goes through prime process before loading filament, somewhere during first layer we actually get material out of the nozzle.

Filament change: 
Seems to feed filament from the next channel over out instead of pulling unloaded filament out. Not jus selector in wrong position, but also feeding in wrong direction?


Z doesn't show up as calibrated, even after mesh bed leveling - I just get a "?" for position.

I've yet to recalibrate distances, but I don't think that's the issue.

There's a LOT of issues here, perhaps too many to sort out. I'm not sure how helpful to be when it's this far off. Can we make SURE I've got the right version of stuff installed, etc?

**Comment by AbeFM** [comment]
> Yes, that’s the FW 👍👌 if you watch the terminal feed of the printer you should see messages about waiting for printer sensor trigger and advising mmu of trigger.
Oh, I could do that, I haven't been.

>If filament stuffs up and doesn’t make it it won’t continue.
??? When/where?

>At this point you should be able to fix the problem. Ensure filament is out back to load position and press middle button to try again and continue.
What problem? 


============
Ok, on a filament change, it backa filament out of extruder, but MMU doesn't take up filament. Selector doesn't move, then it feeds new filament in (looks like not communication with printer) and feeds some ~orange-tube-length of filament out.

I suspect I need to run a orange-tube calibration - perhaps you use new numbers/variables or in a new way? It could be it is retracting "0 mm" or something.

**Comment by AbeFM** [comment]
LASTLY:
Filament calibration doesn't work. I get into the "secret" menu, move over to light #4, hit the button, selector goes to position 5 and it looks like MMU returns to "normal" mode, not doing any calibration at all.

I would *really* appreciated the "patch 1" merge which was functional (from around the 25th?), so I could get some printing done - and then I could test this pair you have knowing I can return to functional at any time.

**Comment by TheZeroBeast** [comment]
Hey man, back online for a bit.

I'll see if I can find Patch1 in git history and get it to you.

> Ok, on a filament change, it backa filament out of extruder, but MMU doesn't take up filament. Selector doesn't move, then it feeds new filament in (looks like not communication with printer) and feeds some ~orange-tube-length of filament out.
This sounds like the MK3 doesn't have the laser filament sensor running, it should be forced on so you may need to confirm in the Settings MK3 menu that it is on.

> I suspect I need to run a orange-tube calibration - perhaps you use new numbers/variables or in a new way? It could be it is retracting "0 mm" or something.
There is no longer a length calibration in the settings menu because it does nothing.
The filament feeds down to about the old minimum tube step count and then pushes slowly checking MK3 filament sensor so each load is spot on.
I was unaware the MK3 sensor could be off after loading firmware, PRUSA code is very confusion so there may be a call from EEPROM disabling it from memory. Good testing, thank you.
Hopefully you are able to enable in menu 👍 and as an improvement I might be able to have print stop before it starts an puts an error in console.

Let me know how you go, and as I said earlier I'll try get the Patch-1 from 25th and zip it on this thread.

Thanks man,
Rob

**Comment by TheZeroBeast** [comment]
Here it is, patch1 before it was merged 👍
[MM-control-01-Patch1.zip](https://github.com/TheZeroBeast/MM-control-01/files/2545654/MM-control-01-Patch1.zip)

**Comment by AbeFM** [comment]
> I'll see if I can find Patch1 in git history and get it to you.
THANKS!!!

> This sounds like the MK3 doesn't have the laser filament sensor running, it should be forced on so you may need to confirm in the Settings MK3 menu that it is on.
Sounds like the MK3 should check! :-P  Yeah, I turn it on and off all the time depending on what problem I most recently had. I'll re-enable! I never saw any text (loading notification) on the screen like you'd mentioned - when would I expect it?

> The filament feeds down to about the old minimum tube length and then pushes slowly checking MK3 filament sensor so each load is spot on.
You mean on EVERY feed, or just once to get a number? I have some materials the sensor doesn't like, I'm happy to try combinations of 'good' and 'bad' ones.

> I was unaware the MK3 sensor could be off after loading firmware, PRUSA code is very confusion so there may be a call from EEPROM disabling it from memory. Good testing, thank you.
I'm guessing it keeps the setting from before flashing. Normal MMU stops to reload filament about 20% of the time during the initial prime if I don't turn off the sensor. I used to think it was a light leak, but now I think it's pure bad code - I don't see a pattern to what triggers it, physically. As mentioned, I'll turn it on and try again.

> Thanks man,
> Rob
No, thank you!


BTW: Are the version numbers that show on the MK3's display (2.0.2-158, 3.4.2-1360) unique? I suspect the 202 is "yours", is 342-1360 just the number of the current prusa Beta?
I don't want to waste your time on bookkeeping, but this gets confusing fast when you don't know what all the pieces are unambiguously.

**Comment by AbeFM** [comment]
Oh! If you're in the Mk3 anyway, leave it off (if user has disabled) to prevent false triggers, but turn it on when you are using it.

Simple enough?

**Comment by AbeFM** [comment]
And I can confirm: The main LCD panel displays "?" instead of a number, even when homed and it knows where it is.

Shouldn't we have separate threads for each "bug"? It's your rodeo, let me know how you'd like to do it. I can make new issues.

**Comment by AbeFM** [comment]
Something's definitely not right. Filament doesn't unload, so selector doesn't move, so filament squirts out wrong side (and stops at default length I think), then it keeps printing with the same material.

I assume this is from the optical sensor. Will reload with PET and see how it goes with same gcode file.

**Comment by AbeFM** [comment]
It's purging before the handoff - the extrudes feeding like it got filament BEFORE the default feed is completed.

And when I cancel print, it's not pulling filament out - seems like the selector may be lost. I can video/characterize/test if you tell me what would be most useful. Will put old firmwares back on until I hear back. :-P

**Comment by TheZeroBeast** [comment]
Hey man,
Just woke up, I’ll check on a couple possible things and get back to you soon.

The 202 is unique and I will chuck a unique version on the MK3 FW today 👍

The feed out from next to selector might be a perpetual loop🤦‍♂️ I think mine did that last night on my way to bed. Keep you posted.

**Comment by TheZeroBeast** [comment]
Hey AbeFM,

I found a nested loop in the fixTheProblem() method that would allow the printer to still request filament change when MMU is waiting to be fixed for failed load/unload. Resulting in selector not moving because filament in it and next filament pushing out.

Let me know how you go with filaments that didn't play nice with MK3 FSensor, that mod to use a bearing would get around this without a new sensor like Chuck did.

**Comment by AbeFM** [comment]
Yeah, I think that's what I saw - it was off by a channel if something went wrong.

Perhaps something like 3 failed loads then re home?

The slicer puts in speed changes if you have TPU selected, I think. Been asking for weeks but I'm just guessing. Anyway, manually putting speed ups in code so my prints don't take 5 days each. Can test firmware combo when you get your next one ready.

**Comment by AbeFM** [comment]
Does it help anything to have removed this? It seems like it doesn't hurt to leave the length tuning in, it's easier than flashing to tune it.

**Pull request merged**
