### PR TITLE
The zero beast testing patch1

### PR DESCRIPTION
**Pull request by TheZeroBeast**
Tested and working so far. further testing and dev required.

if tip is a bit large it is now cut off before loading to bondtech gears.

Rob

### CODE REVIEW

**Comment by AbeFM** [comment]
I'm curious how this cut is done.

I have the 9.9.9-136 I think, quite possibly from a couple hours before this post. Just doing straightforward prints and no real errors yet.

Do we have to overwrite the feed-calibrations each time? This last time I didn't set them and I guess it's working, so we might already be ok here?

Lastly: To do a pull of the latest, I pull here or Karl's?

**Comment by AbeFM** [comment]
Ah, pull didn't do it, but "apply patch" during pull did.

What is this whole cutting thing, what's the logic? I took my blade off, so I'd have to put it back in to test.

**Comment by TheZeroBeast** [comment]
Hey AbeFM,

Yes, feed-cal gets save/loaded from memory each boot so it should be the same after FW

Damn, I should be incrementing build number, I haven't been.

My master, I don't think Karl has pushed any work to his git since the initial release 5 days ago.

Did you see the video I made of the cut sequence on PRUSA forum?

https://shop.prusa3d.com/forum/general-discussion-announcements-and-releases-f53/improvements-to-the-mmu-2-0-controller-firmware-t25189-s50.html

**Comment by AbeFM** [comment]
Ah, ok. When I flashed like, 1.0.1 over 1.0 I lost the cals, so I keep doing it over. Hard to say for sure, so much is so buggy. Working now, anyway, thanks for letting me know not to bother checking till it's an issue.

Oh yeah, numbers are GOOD. Might even make sense to make yours 9.8.x to differentiate it from Karl's, or just use like ZB.1.0-XXX or something.

WOW the filament loads are really fast. Also, noisier. Not like annoying, but you certainly know they are happening. Very.. Smooth sounding.

**Comment by TheZeroBeast** [comment]
Yeah, I like the ZB.1.0, I might go change that now.

Yes, they are and from the limited tested that speed isn't affecting reliability. Sounds smooth because it is doing acceleration and deceleration a lot better. Karl's acceleration code.
If it's too noisy it can be dropped but at this stage for hard plastics it is going to save upto 15% on each tool change. That equates to just under 2h saving on a 700 tool change print. All good if it is reliable and not too noisy.

Beauty of it is that when I get time to code other materials I can just change one variable and have lets say TPU load at a much reduced rate.

**Comment by AbeFM** [comment]
Given that I'm a couple hundred TPU loads in, I'm going to say you can either hold off on the slowdown or increase speed on the harder stuff. :-P

You could potentially reference the material info, it is sent by the printer early in a print.

**Comment by AbeFM** [comment]
I haven't gotten one good top surface since I installed this.

I'm like 95% sure it's me... But just to double check you can still print things with big flat tops?

**Comment by TheZeroBeast** [comment]
I’ll check a few things today that might affect that but I haven’t seen any issues with my tops👍

**Comment by AbeFM** [comment]
Are you pretty sure what you reposted is the same as the last Patch-1?

Even since I've put it on, I get grinding, the selector loses position, etc.

Maybe I just got a bad flash or something, but it is WIGGY how it just
seems like the stock Prusa firmware, except for the quiet startup.

**Comment by TheZeroBeast** [comment]
Yeah, possibly, I try get 30140cb out for you man. Would not expect it to be bug free it was a point in the middle of dev.

Current patch1 is close.

**Comment by AbeFM** [comment]
The one I had was -136, not sure which commit it was.

**Comment by TheZeroBeast** [comment]
Yeah, 30140cb isn't the one, that was just Karl's test setup for demo. Still looking

**Comment by TheZeroBeast** [comment]
[MM-control-01-TheZeroBeast-Testing-Patch1.zip](https://github.com/TheZeroBeast/MM-control-01/files/2556057/MM-control-01-TheZeroBeast-Testing-Patch1.zip)
Here we go, I restored the branch and got a copy. BN: 136 is what is on this one.

**Comment by AbeFM** [comment]
image
I get 999-132 on the screen on this one. I imagine it would be something later. Now that I l know the file the number comes from I may have more luck pulling it myself, though I'm still unsure how to access various versions of stuff through Git. Need to do a couple things then I'll dig.

**Comment by AbeFM** [comment]
Now I have to wonder if I've been smoking the crack. I can't find 999.136 anywhere.
You have 102-131, and 102-132 for a few updates, 999-132 for a few more, then 200-146.

So, um.... Other than an older 1.0.0-1.3.6 I don't see anything matching my description, hence crack use is the only reasonable alternative.

**Comment by AbeFM** [comment]
I am going to stop trying to "figure out" Git before I break something.

**Pull request merged**
